#!/usr/bin/env bash
# Build the namo_complete binary.
#
# Needs a Sun whose stdlib carries sun.process / sun.env / sun.time (the
# 2026-08-19 dev build or newer); an older one fails on the first `using`.
set -euo pipefail

cd "$(dirname "$0")"

: "${SUN_PATH:=/usr/lib/sun}"
export SUN_PATH

if ! command -v sun >/dev/null 2>&1; then
  echo "error: the 'sun' compiler is not on PATH." >&2
  echo "       install it with ./install.sh, or see https://namo-robotics.github.io/sun/" >&2
  exit 1
fi

mkdir -p bin

# Stamp the build. src/version.sun is generated, never committed: an installed
# binary has to be able to say which commit it came from, because "reinstall and
# see" is not an answer when the release tag is rolling.
git_() { git -c safe.directory='*' "$@" 2>/dev/null; }
VERSION="${NAMO_VERSION:-$(git_ describe --tags --always --dirty || echo unknown)}"
COMMIT="$(git_ rev-parse HEAD || echo "${GITHUB_SHA:-}")"
COMMIT="${COMMIT:0:12}"
[ -n "$COMMIT" ] || COMMIT="unknown"
git_ diff --quiet HEAD || COMMIT="$COMMIT-dirty"
BUILT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BUILT_WITH="${NAMO_BUILT_WITH:-$(sun --version 2>/dev/null | head -1)}"
esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

cat > src/version.sun <<SUNEOF
// version.sun - generated by build.sh. Not committed; regenerated every build.
public module namo {
  using sun;

  public var VERSION: static_ptr<u8> = "$(esc "$VERSION")";
  public var COMMIT: static_ptr<u8> = "$(esc "$COMMIT")";
  public var BUILT: static_ptr<u8> = "$(esc "$BUILT")";
  public var BUILT_WITH: static_ptr<u8> = "$(esc "$BUILT_WITH")";
}
SUNEOF

echo "building bin/namo_complete $VERSION ($COMMIT) ..."
if ! sun -c -o bin/namo_complete src/main.sun; then
  echo >&2
  echo "error: build failed. If the errors mention 'sun.process', 'sun.env' or" >&2
  echo "       an unknown member on a stdlib type, the installed Sun predates" >&2
  echo "       the stdlib modules this project needs. Update it:" >&2
  echo "         curl -LO https://github.com/namo-robotics/sun/releases/download/dev/sun_0.dev_amd64.deb" >&2
  echo "         sudo apt install ./sun_0.dev_amd64.deb" >&2
  exit 1
fi

echo
echo "built: bin/namo_complete"
file bin/namo_complete | sed 's/^/  /'
