#!/usr/bin/env bash
# Build the namo_complete binary with the current Sun dev toolchain.
set -euo pipefail

cd "$(dirname "$0")"

if ! command -v sun >/dev/null 2>&1; then
  echo "error: the Sun compiler is not on PATH." >&2
  echo "       install the latest dev artifact from https://github.com/namo-robotics/sun/releases/tag/dev" >&2
  exit 1
fi

# An unpacked toolchain keeps its target-matched bundles beside the compiler.
if [ -z "${SUN_PATH:-}" ]; then
  SUN_BIN=$(command -v sun)
  SUN_PREFIX=$(cd "$(dirname "$SUN_BIN")/.." 2>/dev/null && pwd -P || true)
  if [ -n "$SUN_PREFIX" ] && [ -f "$SUN_PREFIX/lib/sun/stdlib.moon" ]; then
    SUN_PATH="$SUN_PREFIX/lib/sun"
    export SUN_PATH
  fi
fi
# Both precompiled libraries must come from one release artifact.
BUNDLE_DIR=""
OLD_IFS=$IFS
IFS=:
for dir in ${SUN_PATH:-}; do
  if [ -f "$dir/stdlib.moon" ] && [ -f "$dir/tls.moon" ]; then BUNDLE_DIR=$dir; break; fi
done
IFS=$OLD_IFS
unset OLD_IFS
if [ -z "$BUNDLE_DIR" ]; then
  echo "error: matching stdlib.moon and tls.moon were not found in SUN_PATH (${SUN_PATH:-unset})." >&2
  echo "       install one complete artifact from https://github.com/namo-robotics/sun/releases/tag/dev" >&2
  exit 1
fi

case "$(uname -s):$(uname -m)" in
  Linux:x86_64|Linux:amd64) NAMO_PLATFORM=linux-x86_64 ;;
  Darwin:arm64) NAMO_PLATFORM=macos-arm64 ;;
  *) echo "error: unsupported build host $(uname -s)/$(uname -m); expected Linux x86_64 or macOS arm64." >&2; exit 1 ;;
esac

BUILT_WITH=${NAMO_BUILT_WITH:-$(sun --version 2>/dev/null | head -1)}
case "$BUILT_WITH" in
  "sun 0.dev ("*|"sun dev ("*|*dirty*) ;;
  *) echo "warning: expected a Sun dev release; building with: $BUILT_WITH" >&2 ;;
esac

mkdir -p bin

# Stamp the build so a rolling dev artifact can be identified precisely.
git_() { git -c safe.directory="*" "$@" 2>/dev/null; }
VERSION=${NAMO_VERSION:-$(git_ describe --tags --always --dirty || echo unknown)}
COMMIT=$(git_ rev-parse HEAD || echo "${GITHUB_SHA:-}")
COMMIT=${COMMIT:0:12}
[ -n "$COMMIT" ] || COMMIT=unknown
git_ diff --quiet HEAD || COMMIT="$COMMIT-dirty"
BUILT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
esc() { printf "%s" "$1" | sed "s/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g"; }

cat > src/version.sun <<SUNEOF
// version.sun - generated by build.sh. Not committed; regenerated every build.
public module namo {
  using std;

  // Release or source description for this build.
  public var VERSION: static_ptr<u8> = "$(esc "$VERSION")";
  // Source commit embedded in this build.
  public var COMMIT: static_ptr<u8> = "$(esc "$COMMIT")";
  // UTC time when this build was produced.
  public var BUILT: static_ptr<u8> = "$(esc "$BUILT")";
  // Sun compiler version used for this build.
  public var BUILT_WITH: static_ptr<u8> = "$(esc "$BUILT_WITH")";
}
SUNEOF

echo "building bin/namo_complete $VERSION ($COMMIT) for $NAMO_PLATFORM ..."
if ! sun -c -o bin/namo_complete src/main.sun; then
  echo >&2
  echo "error: build failed with $BUILT_WITH." >&2
  echo "       Install the latest Sun dev artifact, including matching stdlib.moon and tls.moon bundles:" >&2
  echo "       https://github.com/namo-robotics/sun/releases/tag/dev" >&2
  exit 1
fi

echo
echo "built: bin/namo_complete"
file bin/namo_complete | sed "s/^/  /"
